name: Guardrail-CI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-guardrail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install typer rich requests pyyaml jinja2
      - name: Run Guardrail Test
        run: python -m guardrail_ai test --adapter openai --endpoint https://dummy --auth-key dummy --prompt "test prompt"
      - name: Run Guardrail Evaluation (will fail on thresholds with dummy key)
        run: python -m guardrail_ai evaluate --adapter openai --endpoint https://dummy --auth-key dummy --prompts-file assets/eu_ai_prompts.yaml --output-file outputs/ci_report.json --html-report outputs/ci_report.html
        continue-on-error: true
